export class ClientModel {
   id:any;
   NomClient:any;
   PrenomClient:any;
   Civilite:any;
   Societe:any;
   Telephone:any;
   Email:any;
   DateNaissance:any;
   Adresse:any;
   Ville:any;
   CodePostal:any;
   Batiment:any;
   Etage:any;
   Sonette:any;
   Code1:any;
   Code2:any;
   Code3:any;
   Commentaire:any;
   Montantfidilite:any;
   Codebarre:any;
   NbrComa:any;
   type:any;
 }
